# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  stl_config = debug
endif
ifeq ($(config),release)
  stl_config = release
endif
ifeq ($(config),dist)
  stl_config = dist
endif

PROJECTS := stl

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

stl:
ifneq (,$(stl_config))
	@echo "==== Building stl ($(stl_config)) ===="
	@${MAKE} --no-print-directory -C stlproj -f Makefile config=$(stl_config)
endif

clean:
	@${MAKE} --no-print-directory -C stlproj -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   stl"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"